/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-TETRA_DMO
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_TETRA_DMO_API_H
#define INCLUDED_TETRA_DMO_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_TETRA_DMO_EXPORTS
#define TETRA_DMO_API __GR_ATTR_EXPORT
#else
#define TETRA_DMO_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_TETRA_DMO_API_H */
