/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(MAC_DECODER.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3bf798db333537af4e4a04715fd945ac)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/TETRA_DMO/MAC_DECODER.h>
// pydoc.h is automatically generated in the build directory
#include <MAC_DECODER_pydoc.h>

void bind_MAC_DECODER(py::module& m)
{

    using MAC_DECODER    = gr::TETRA_DMO::MAC_DECODER;


    py::class_<MAC_DECODER, gr::block, gr::basic_block,
        std::shared_ptr<MAC_DECODER>>(m, "MAC_DECODER", D(MAC_DECODER))

        .def(py::init(&MAC_DECODER::make),
           D(MAC_DECODER,make)
        )
        



        ;




}








